# Generated by Django 5.0.1 on 2024-01-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='get_sex',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=6),
        ),
    ]
